"""Generado automaticamente por generar_destinos_eurostat.py
Fuente: Eurostat tour_occ_nin2, año 2024, 294 regiones NUTS2.
Incluye TODAS las regiones del dataset (saturadas y no saturadas),
sin filtro adicional -- el propio dataset ya mide actividad turistica real.
"""

DESTINOS_CAPA3A = [
    ['Veri', 'Qender', 'Jug', 'Burgenland', 'Niederösterreich'],
    ['Wien', 'Kärnten', 'Steiermark', 'Oberösterreich', 'Salzburg'],
    ['Tirol', 'Vorarlberg', 'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest', 'Prov. Antwerpen', 'Prov. Limburg'],
    ['Prov. Oost-Vlaanderen', 'Prov. Vlaams-Brabant', 'Prov. West-Vlaanderen', 'Prov. Brabant wallon', 'Prov. Hainaut'],
    ['Prov. Liège', 'Prov. Luxembourg', 'Prov. Namur', 'Severozapaden', 'Severen tsentralen'],
    ['Severoiztochen', 'Yugoiztochen', 'Yugozapaden', 'Yuzhen tsentralen', 'Région lémanique'],
    ['Espace Mittelland', 'Nordwestschweiz', 'Zürich', 'Ostschweiz', 'Zentralschweiz'],
    ['Ticino', 'Kýpros', 'Praha', 'Střední Čechy', 'Jihozápad'],
    ['Severozápad', 'Severovýchod', 'Jihovýchod', 'Střední Morava', 'Moravskoslezsko'],
    ['Stuttgart', 'Karlsruhe', 'Freiburg', 'Tübingen', 'Oberbayern'],
    ['Niederbayern', 'Oberpfalz', 'Oberfranken', 'Mittelfranken', 'Unterfranken'],
    ['Schwaben', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg'],
    ['Darmstadt', 'Gießen', 'Kassel', 'Mecklenburg-Vorpommern', 'Braunschweig'],
    ['Hannover', 'Lüneburg', 'Weser-Ems', 'Düsseldorf', 'Köln'],
    ['Münster', 'Detmold', 'Arnsberg', 'Koblenz', 'Trier'],
    ['Rheinhessen-Pfalz', 'Saarland', 'Dresden', 'Chemnitz', 'Leipzig'],
    ['Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen', 'Hovedstaden', 'Sjælland'],
    ['Syddanmark', 'Midtjylland', 'Nordjylland', 'Eesti', 'Attiki'],
    ['Voreio Aigaio', 'Notio Aigaio', 'Kriti', 'Anatoliki Makedonia, Thraki', 'Kentriki Makedonia'],
    ['Dytiki Makedonia', 'Ipeiros', 'Thessalia', 'Ionia Nisia', 'Dytiki Elláda'],
    ['Sterea Elláda', 'Peloponnisos', 'Galicia', 'Principado de Asturias', 'Cantabria'],
    ['País Vasco', 'Comunidad Foral de Navarra', 'La Rioja', 'Aragón', 'Comunidad de Madrid'],
    ['Castilla y León', 'Castilla-La Mancha', 'Extremadura', 'Cataluña', 'Comunitat Valenciana'],
    ['Illes Balears', 'Andalucía', 'Región de Murcia', 'Ciudad de Ceuta', 'Ciudad de Melilla'],
    ['Canarias', 'Länsi-Suomi', 'Helsinki-Uusimaa', 'Etelä-Suomi', 'Pohjois- ja Itä-Suomi'],
    ['Åland', 'Ile de France', 'Centre — Val de Loire', 'Bourgogne', 'Franche-Comté'],
    ['Basse-Normandie', 'Haute-Normandie', 'Nord-Pas de Calais', 'Picardie', 'Alsace'],
    ['Champagne-Ardenne', 'Lorraine', 'Pays de la Loire', 'Bretagne', 'Aquitaine'],
    ['Limousin', 'Poitou-Charentes', 'Languedoc-Roussillon', 'Midi-Pyrénées', 'Auvergne'],
    ['Rhône-Alpes', 'Provence-Alpes-Côte d’Azur', 'Corse', 'Guadeloupe', 'Martinique'],
    ['Guyane', 'La Réunion', 'Mayotte', 'Panonska Hrvatska', 'Jadranska Hrvatska'],
    ['Grad Zagreb', 'Sjeverna Hrvatska', 'Budapest', 'Pest', 'Közép-Dunántúl'],
    ['Nyugat-Dunántúl', 'Dél-Dunántúl', 'Észak-Magyarország', 'Észak-Alföld', 'Dél-Alföld'],
    ['Northern and Western', 'Southern', 'Eastern and Midland', 'Piemonte', 'Valle d’Aosta/Vallée d’Aoste'],
    ['Liguria', 'Lombardia', 'Abruzzo', 'Molise', 'Campania'],
    ['Puglia', 'Basilicata', 'Calabria', 'Sicilia', 'Sardegna'],
    ['Provincia Autonoma di Bolzano/Bozen', 'Provincia Autonoma di Trento', 'Veneto', 'Friuli-Venezia Giulia', 'Emilia-Romagna'],
    ['Toscana', 'Umbria', 'Marche', 'Lazio', 'Liechtenstein'],
    ['Sostinės regionas', 'Vidurio ir vakarų Lietuvos regionas', 'Luxembourg', 'Latvija', 'Crna Gora'],
    ['Severna Makedonija', 'Malta', 'Groningen', 'Friesland', 'Drenthe'],
    ['Overijssel', 'Gelderland', 'Flevoland', 'Noord-Holland', 'Zeeland'],
    ['Utrecht', 'Zuid-Holland', 'Noord-Brabant', 'Limburg', 'Innlandet'],
    ['Trøndelag', 'Nord-Norge', 'Oslo og Viken', 'Agder og Sør-Østlandet', 'Vestlandet'],
    ['Svalbard og Jan Mayen', 'Małopolskie', 'Śląskie', 'Wielkopolskie', 'Zachodniopomorskie'],
    ['Lubuskie', 'Dolnośląskie', 'Opolskie', 'Kujawsko-pomorskie', 'Warmińsko-mazurskie'],
    ['Pomorskie', 'Łódzkie', 'Świętokrzyskie', 'Lubelskie', 'Podkarpackie'],
    ['Podlaskie', 'Warszawski stołeczny', 'Mazowiecki regionalny', 'Norte', 'Algarve'],
    ['Centro', 'Grande Lisboa', 'Península de Setúbal', 'Alentejo', 'Oeste e Vale do Tejo'],
    ['Região Autónoma dos Açores', 'Região Autónoma da Madeira', 'Nord-Vest', 'Centru', 'Nord-Est'],
    ['Sud-Est', 'Sud-Muntenia', 'Bucureşti-Ilfov', 'Sud-Vest Oltenia', 'Vest'],
    ['Beogradski region', 'Region Vojvodine', 'Region Sumadije i Zapadne Srbije', 'Region Juzne i Istocne Srbije', 'Stockholm'],
    ['Östra Mellansverige', 'Småland med öarna', 'Sydsverige', 'Västsverige', 'Norra Mellansverige'],
    ['Mellersta Norrland', 'Övre Norrland', 'Vzhodna Slovenija', 'Zahodna Slovenija', 'Bratislavský kraj'],
    ['Západné Slovensko', 'Stredné Slovensko', 'Východné Slovensko', 'İstanbul', 'Tekirdağ, Edirne, Kırklareli'],
    ['Balıkesir, Çanakkale', 'İzmir', 'Aydın, Denizli, Muğla', 'Manisa, Afyonkarahisar, Kütahya, Uşak', 'Bursa, Eskişehir, Bilecik'],
    ['Kocaeli, Sakarya, Düzce, Bolu, Yalova', 'Ankara', 'Konya, Karaman', 'Antalya, Isparta, Burdur', 'Adana, Mersin'],
    ['Hatay, Kahramanmaraş, Osmaniye', 'Kırıkkale, Aksaray, Niğde, Nevşehir, Kırşehir', 'Kayseri, Sivas, Yozgat', 'Zonguldak, Karabük, Bartın', 'Kastamonu, Çankırı, Sinop'],
    ['Samsun, Tokat, Çorum, Amasya', 'Trabzon, Ordu, Giresun, Rize, Artvin, Gümüşhane', 'Erzurum, Erzincan, Bayburt', 'Ağrı, Kars, Iğdır, Ardahan', 'Malatya, Elazığ, Bingöl, Tunceli'],
    ['Van, Muş, Bitlis, Hakkari', 'Gaziantep, Adıyaman, Kilis', 'Şanlıurfa, Diyarbakır', 'Mardin, Batman, Şırnak, Siirt'],
]
